spring:
  datasource:
    druid:
      url: jdbc:mysql://10.6.20.18:3306/newsappdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80

mybatis:
  type-aliases-package: com.zxtt.newsapp.commons.entity
  mapperLocations: classpath:mapper/*.xml



logging:
  level:
    com.zxtt.newsapp.commons.mapper : debug  #dao的路径